### ISSUE TITLE
localhost:8080-》404

### ISSUE THREAD

**Issue by justforhing** [xuxueli/xxl-code-generator#18]
请问有项目运行成功，使用localhost:8080报404的吗？

**Comment by alice45** [comment]
![image](https://user-images.githubusercontent.com/26273358/72513974-d3e61380-3888-11ea-9800-6d71d786faa5.png)

因为yml中配置了内嵌tomcat的context-path，访问http://localhost:8080/xxl-code-generator/就行了

**Comment by xuxueli** [comment]
@alice45 +1
